version:          "3.4"

x-env-files:      &env-files
  env_file:
    - .env

volumes:
  cluster_data_vol:

services:                         # Path to dockerfile.

  mysql-manager-1:
    image:        mysql-cluster
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      ndb_mgmd --ndb-nodeid=1

  mysql-manager-2:
    image:        mysql-cluster
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      ndb_mgmd --ndb-nodeid=2

  mysql-manager-3:
    image:        mysql-cluster
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      ndb_mgmd --ndb-nodeid=3



  data-node-1:
    image:        mysql-cluster
    <<:           *env-files
    depends_on: 
      - mysql-manager-1
      - mysql-manager-2
      - mysql-manager-3
    networks:
      - db-network
    restart:      always
    volumes:
      - cluster_data_vol:/var/lib/mysql
    command:      ndbd --ndb-nodeid=11 --nowait-nodes=4 --initial-start --connect-string="nodeid=1;host=mysql-manager-1:1186"

  data-node-2:
    image:        mysql-cluster
    <<:           *env-files
    depends_on: 
      - mysql-manager-1
      - mysql-manager-2
      - mysql-manager-3
    networks:
      - db-network
    restart:      always
    volumes:
      - cluster_data_vol:/var/lib/mysql
    command:      ndbd --ndb-nodeid=12 --nowait-nodes=4 --initial-start --connect-string="nodeid=1;host=mysql-manager-1:1186"
    
    
  data-node-3:
    image:        mysql-cluster
    <<:           *env-files
    depends_on: 
      - mysql-manager-1
      - mysql-manager-2
      - mysql-manager-3
    networks:
      - db-network
    restart:      always
    volumes:
      - cluster_data_vol:/var/lib/mysql
    command:      ndbd --ndb-nodeid=13 --nowait-nodes=4 --initial-start --connect-string="nodeid=1;host=mysql-manager-1:1186"
    

  mysql-server-1:
    image:        mysql-cluster
    <<:           *env-files
    depends_on: 
      - mysql-manager-1
      - mysql-manager-2
      - mysql-manager-3
    networks:
      - db-network
    restart:      always
    command:      mysqld --user=mysql --connect-string="nodeid=1;host=mysql-manager-1:1186;host=mysql-manager-2:1186"
    ports:
      - 3000:3000

  mysql-server-2:
    image:        mysql-cluster
    <<:           *env-files
    depends_on: 
      - mysql-manager-1
      - mysql-manager-2
      - mysql-manager-3
    networks:
      - db-network
    restart:      always
    command:      mysqld --user=mysql --connect-string="nodeid=1;host=mysql-manager-1:1186;host=mysql-manager-2:1186"
    ports:
      - 3001:3000
      
      
  mysql-server-3:
    image:        mysql-cluster
    <<:           *env-files
    depends_on: 
      - mysql-manager-1
      - mysql-manager-2
      - mysql-manager-3
    networks:
      - db-network
    restart:      always
    command:      mysqld --user=mysql --connect-string="nodeid=1;host=mysql-manager-1:1186;host=mysql-manager-2:1186"
    ports:
      - 3002:3000    

networks:
  db-network:
